#!/usr/bin/env python

import os
import sys


def highlight(string):
    """Highlight text when supported"""
    if sys.stdout.isatty():
        string = '\x1b[%sm%s\x1b[0m' % (';31', string)

    return string


def get_command():
    """Form command to pass to git repos"""
    global sys

    # Remove the first item, which is the script name
    del sys.argv[0]
    return ' '.join(sys.argv)


def main():
    # Make sure there's at least 1 command to pass to the repos
    if 2 > len(sys.argv):
        sys.exit("You need to include a command to run on each repository: e.g. git pluck pull")

    # Process `--nogit` flag
    if '--nogit' == sys.argv[1] or '--nogit' == sys.argv[-1]:
        sys.argv.remove('--nogit')
        command = get_command()
    else:
        command = "git %s" % get_command()

    # Recurse through git repos
    for root, directories, files in os.walk(os.getcwd()):
        # Skip directories that aren't git roots
        if not os.path.isdir(root + '/.git'):
            continue

        # Get the relative path of the repo
        relpath = os.path.relpath(root, os.getcwd())
        print "Entering '%s'" % highlight(relpath)

        # Pass the command into each repository
        print os.popen("cd %s && %s" % (root, command)).read()

if __name__ == '__main__':
    main()
