#!/usr/bin/env python

import os
import argparse

# Parse args
parser = argparse.ArgumentParser(description='Automate git updates')
parser.add_argument('-a', '--all', help='Automatically pull all found repositories', action='store_true')
args = vars(parser.parse_args())

for root, directories, files in os.walk(os.getcwd()):
    # Skip directories that aren't git roots
    if not os.path.isdir(root + '/.git'):
        continue

    # Give the chance to skip certain repos if the all flag isn't set
    if not args['all']:
        confirm = raw_input("Update repository: %s?\nType 'n' for no, <enter> for yes: " % root)
        if 'n' == confirm:
            continue

    # Get the current branch name
    branch = os.popen("cd %s && git symbolic-ref --short -q HEAD" % root).read()
    # Get the relative path of the repo
    relpath = os.path.relpath(root, os.getcwd())
    # Explain what's happening
    print "Updating", relpath, "on branch", branch,

    # Try to do the pull
    os.system("cd %s && git pull" % root)
    print "\n",
